'''
fibonacci series is a series that is generated by the addition of the two preciding numbers
This will be a small application that will determine if the number is a fibonacci number
Example is (0,1,1,2,3,5,8,13,21,34...)

'''

from unicodedata import digit


def find_if_fibonacci():

    num = int(input("Hi there. Kindly input the number you want to check...\n\n"))

    digit1 = 0
    digit2 = 1
    summation = digit1 + digit2

    if num <= 0:
        print("Error: kindly input a value that is greater than 0")
    else:
        for i in range(0, num):
            digit1 = digit2
            digit2 = summation
            summation = digit1 + digit2

            print(summation, end=" ")

find_if_fibonacci()